version: '3.8'
services:
  booking-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-service
    image: searchservice
    ports:
      - "8083:8083"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/userdb
    depends_on:
      - mongodb
    networks:
      - backend

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - backend

networks:
  backend:
    driver: bridge