name: CI Pipeline for SearchService

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up JDK
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'


      # Step 3: Build with Maven
      - name: Build with Maven
        run: mvn clean package

      # Step 4: Run Unit Tests
      - name: Run Tests
        run: mvn test

      # Step 5: Upload Build Artifact
      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v3
        with:
          name: search-service-jar
          path: target/SearchService-0.0.1-SNAPSHOT.jar